const dotenv = require("dotenv");

dotenv.config();

const env = {
  nodeEnv: process.env.NODE_ENV || "development",
  port: Number(process.env.PORT || 5000),
  jwtSecret: process.env.JWT_SECRET || "change-me-in-production",
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || "change-me-refresh-secret",
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || "1h",
  jwtRefreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || "7d",
  mysqlHost: process.env.MYSQL_HOST || "localhost",
  mysqlPort: Number(process.env.MYSQL_PORT || 3307),
  mysqlUser: process.env.MYSQL_USER || "root",
  mysqlPassword: process.env.MYSQL_PASSWORD || "",
  mysqlDatabase: process.env.MYSQL_DATABASE || "restaurant_saas",
  frontendUrl: process.env.FRONTEND_URL || "http://localhost:5173",
  defaultAdminEmail: process.env.DEFAULT_ADMIN_EMAIL || "Vitasystemsai@gmail.com",
  defaultAdminPassword: process.env.DEFAULT_ADMIN_PASSWORD || "Vita@2025",
  defaultAdminName: process.env.DEFAULT_ADMIN_NAME || "Platform Admin",
  smtpHost: process.env.SMTP_HOST || "",
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpSecure: String(process.env.SMTP_SECURE || "false").toLowerCase() === "true",
  smtpUser: process.env.SMTP_USER || "",
  smtpPass: process.env.SMTP_PASS || "",
  smtpFromEmail: process.env.SMTP_FROM_EMAIL || process.env.SMTP_USER || "",
  smtpFromName: process.env.SMTP_FROM_NAME || "feeasto.com",
  otpCodeLength: Number(process.env.OTP_CODE_LENGTH || 6),
  otpTtlMinutes: Number(process.env.OTP_TTL_MINUTES || 10),
  otpMaxAttempts: Number(process.env.OTP_MAX_ATTEMPTS || 5),
  otpResendCooldownSeconds: Number(process.env.OTP_RESEND_COOLDOWN_SECONDS || 45),
  resetOtpTtlMinutes: Number(process.env.RESET_OTP_TTL_MINUTES || 5),
  resetOtpMaxAttempts: Number(process.env.RESET_OTP_MAX_ATTEMPTS || 5),
  resetOtpMaxResends: Number(process.env.RESET_OTP_MAX_RESENDS || 3),
  resetOtpResendCooldownSeconds: Number(process.env.RESET_OTP_RESEND_COOLDOWN_SECONDS || 60),
  resetTokenExpiresIn: process.env.RESET_TOKEN_EXPIRES_IN || "15m",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID || "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN || "",
  twilioFromNumber: process.env.TWILIO_FROM_NUMBER || "",
  smsProvider: process.env.SMS_PROVIDER || "",
  smsWebhookUrl: process.env.SMS_WEBHOOK_URL || "",
  /** India SMS — set at least one for real OTP delivery */
  twofactorApiKey: process.env.TWOFACTOR_API_KEY || "",
  twofactorOtpTemplate: process.env.TWOFACTOR_OTP_TEMPLATE || "FEAOTP",
  textlocalApiKey: process.env.TEXTLOCAL_API_KEY || "",
  textlocalSender: process.env.TEXTLOCAL_SENDER || "",
  msg91AuthKey: process.env.MSG91_AUTH_KEY || "",
  msg91SenderId: process.env.MSG91_SENDER_ID || "FEASTR",
  msg91OtpMessage: process.env.MSG91_OTP_MESSAGE || "",
  fast2SmsApiKey: process.env.FAST2SMS_API_KEY || "",
  mapplsAccessToken: process.env.MAPPLS_ACCESS_TOKEN || "",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY || "",
};

module.exports = env;
